#!/bin/sh
SCRIPTS_STYLES=$(git diff --cached --name-only --diff-filter=ACM "*.ts" "*.js" "*.css" | sed 's| |\\ |g')
[ -z "$SCRIPTS_STYLES" ] && exit 0

# run prettier against files in check mode
# reject in case of errors
echo "$SCRIPTS_STYLES" | xargs ./node_modules/.bin/prettier --c --loglevel error
if [ $? != 0 ]; then
        cat<<\EOF
Prettier lint check failed, please run prettier
against changes.
EOF
        exit 1
fi

SCRIPTS=$(git diff --cached --name-only --diff-filter=ACM "*.ts" "*.js" | sed 's| |\\ |g')
[ -z "$SCRIPTS" ] && exit 0

# run eslint against files
# reject in case of errors
echo "$SCRIPTS" | xargs ./node_modules/.bin/eslint
if [ $? != 0 ]; then
	cat<<\EOF
ESLint check failed, please run eslint against changes.
EOF
	exit 1
fi

exit 0
